### ISSUE TITLE
Switching to MIT license

### ISSUE THREAD

**Issue by ArcticTheRogue** [ArcticTheRogue/random-go-stuff#3]
I think I need to check if everyone is ok with license changes so here it is

**Comment by ArcticTheRogue** [comment]
@Dazage are you ok with switching the license to MIT?

**Comment by Dazage** [comment]
lmao it's your project, do what you want I'm just here to help you

**Comment by ArcticTheRogue** [comment]
lol yeah ik just asking as iirc you are legally supposed to do this if there are other commits so just doing it
thanks
